config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable' if Rails.env.production?
  # get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { registrations: 'registrations' }

  authenticate :user do
    mount GoodJob::Engine => '/good_job'
    mount ExceptionTrack::Engine => '/exception-track'
    mount RailsPerformance::Engine => '/performance'
    mount PgHero::Engine => '/pghero'
  end

  root 'feeds#index'

  resources :settings, only: %i[index create update]
  resources :games, only: %i[index show destroy]
  resources :game_black_lists, only: %i[index create destroy]
  resources :products
  resources :image_layers, only: %i[new create show update destroy]
  resources :avitos, only: [:index]
  post '/update_img', to: 'jobs#update_img'
  get '/feeds', to: 'feeds#index'

  resources :stores do
    draw :avito
    get '/avito', to: 'avito/dashboard#index'

    post '/update_feed', to: 'jobs#update_feed', as: 'update_feed'
    post '/update_ban_list', to: 'jobs#update_ban_list'
    post '/update_store_test_img', to: 'jobs#update_store_test_img'
    patch '/update_all', to: 'ads#update_all'

    resources :streets, only: %i[index create update destroy]
    resources :maps, only: [:show]
    resources :addresses, only: %i[new create show update destroy]
    resources :ads, only: %i[edit update]
  end
end

app/models/store.rb
class Store < ApplicationRecord
  validates :var, presence: true, uniqueness: { scope: :user_id }
  validates :category, presence: true
  validates :goods_type, presence: true
  validates :ad_type, presence: true
  validates :type, presence: true
  validates :description, presence: true
  validates :condition, presence: true
  validates :allow_email, presence: true
  validates :manager_name, presence: true
  validates :contact_phone, presence: true, uniqueness: { case_sensitive: false }

  has_many :image_layers, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :avito_tokens, dependent: :destroy
  has_many :ban_lists, dependent: :destroy
  has_many :ads, dependent: :destroy
  has_many :cache_reports, dependent: :destroy

  has_one_attached :test_img, dependent: :purge

  belongs_to :user

  before_save :set_default_layer_params, :cleanup_description

  self.inheritance_column = :type_

  scope :active, -> { where(active: true) }

  private

  def set_default_layer_params
    game_img_params.present? || self.game_img_params = nil
  end

  def cleanup_description
    return if description.blank?

    description.squeeze!(' ')
    description.strip!
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :authenticate_user!
  before_action :set_store, only: %i[show edit update destroy]
  before_action :set_search_ads, only: :show
  add_breadcrumb 'Главная', :root_path
  before_action :set_breadcrumb, only: %i[index show new edit]

  def index
    @stores = current_user.stores.order(active: :desc).order(:created_at)
  end

  def show
    add_breadcrumb @store.manager_name, store_path(@store)
    @pagy, @ads   = pagy(@q_ads.result, items: 36)
    @addresses    = @store.addresses.includes(:streets, image_attachment: :blob).order(:id)
    @image_layers = @store.image_layers.includes(layer_attachment: :blob).order(:menuindex, :id)
  end

  def new
    @store = current_user.stores.build
  end

  def edit; end

  def create
    @store = current_user.stores.build(store_params)

    if @store.save
      msg = ["Магазин #{@store.manager_name} был успешно добавлен."]
      msg << 'Внимание магазин не активен!' if store_params[:active].to_i.zero?
      flash[:success] = msg
      redirect_to @store
    else
      error_notice(@store.errors.full_messages)
    end
  end

  def update
    if @store.update(store_params)
      msg = ["Магазин #{@store.manager_name} был успешно обновлен."]
      msg << 'Внимание магазин не активен!' if store_params[:active].to_i.zero?
      flash[:success] = msg
      redirect_to @store
    else
      error_notice(@store.errors.full_messages)
    end
  end

  def destroy
    if @store.destroy
      msg = "Магазин #{@store.manager_name} был успешно удален."
      render turbo_stream: [turbo_stream.remove("store_#{@store.id}"), success_notice(msg)]
    else
      error_notice(@store.errors.full_messages)
    end
  end

  private

  def set_breadcrumb
    add_breadcrumb 'Аккаунты', stores_path
  end

  def store_params
    params.require(:store)
          .permit(:manager_name, :var, :ad_status, :category, :goods_type, :ad_type, :type, :desc_game,
                  :menuindex, :active, :contact_method, :description, :condition, :desc_product, :percent,
                  :allow_email, :contact_phone, :game_img_params, :table_id, :client_id, :client_secret)
  end
end

app/helpers/stores_helper.rb
module StoresHelper
  STORE_ELEMENTS = %w[div span ul li br b i strong em p].freeze

  private

  def sanitize_description(value)
    sanitize(value, { elements: STORE_ELEMENTS })
  end
end

app/views/stores/_form.html.erb
<%= form_with(model: @store, url: url, method: method) do |form| %>
  <div class="mb-3">
    <%= form.label :manager_name, class: 'form-label' %>
    <%= form.text_field :manager_name, class: 'form-control', placeholder: 'Manager name' %>
  </div>

  <div class="mb-3">
    <%= form.label :var, class: 'form-label' %>
    <%= form.text_field :var, class: 'form-control', placeholder: 'var' %>
  </div>

  <div class="mb-3">
    <%= form.label :ad_status, class: 'form-label' %>
    <%= form.text_field :ad_status, class: 'form-control', placeholder: 'Ad status' %>
  </div>

  <div class="mb-3">
    <%= form.label :category, class: 'form-label' %>
    <%= form.text_field :category, value: @store.category || 'Игры, приставки и программы',
                        class: 'form-control', placeholder: 'Category' %>
  </div>

  <div class="mb-3">
    <%= form.label :goods_type, class: 'form-label' %>
    <%= form.text_field :goods_type, value: @store.goods_type || 'Игры для приставок',
                        class: 'form-control', placeholder: 'Игры для приставок' %>
  </div>

  <div class="mb-3">
    <%= form.label :ad_type, class: 'form-label' %>
    <%= form.text_field :ad_type, value: @store.ad_type || 'Товар приобретен на продажу',
                        class: 'form-control', placeholder: 'Товар приобретен на продажу' %>
  </div>

  <div class="mb-3">
    <%= form.label :type, class: 'form-label' %>
    <%= form.text_field :type, value: @store.type || 'Другое', class: 'form-control', placeholder: 'Другое' %>
  </div>

  <div class="mb-3">
    <%= form.label :description, 'Общее описание', class: 'form-label' %>
    <%= form.rich_text_area :description, size: '50x7', class: 'form-control', placeholder: 'Description' %>
  </div>

  <div class="mb-3">
    <label for="desc_game" class="form-label">Описание для Игр</label>
    <%= form.rich_text_area :desc_game, size: '50x5', class: 'form-control', placeholder: 'Описание для Игр' %>
  </div>

  <div class="mb-3">
    <label for="desc_product" class="form-label">Описание для других объявлений</label>
    <%= form.rich_text_area :desc_product, size: '50x5',
                            class: 'form-control', placeholder: 'Описание для других объявлений' %>
  </div>

  <div class="mb-3">
    <label for="condition" class="form-label">Condition</label>
    <%= form.text_field :condition, value: @store.condition || 'Новое', class: 'form-control', placeholder: 'Новое' %>
  </div>

  <div class="mb-3">
    <label for="allow_email" class="form-label">Allow email</label>
    <%= form.text_field :allow_email, value: @store.allow_email || 'Нет', class: 'form-control', placeholder: 'Нет' %>
  </div>

  <div class="mb-3">
    <%= form.label :contact_phone, class: 'form-label' %>
    <%= form.text_field :contact_phone, class: 'form-control', placeholder: 'Телефон' %>
  </div>

  <div class="mb-3">
    <label for="contact_method" class="form-label">Способ связи</label>
    <%= form.select :contact_method, options_for_select(['По телефону и в сообщениях', 'По телефону', 'В сообщениях'],
                                                        @store.contact_method), {}, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <label for="game_img_params" class="form-label">Параметры картинки игры</label>
    <%= form.text_field :game_img_params, class: 'form-control',
                       placeholder: "Нужно указать ввиде json: { pos_x: 448, pos_y: 208, row: 1024, column: 1024 }" %>
  </div>

  <div class="mb-3">
    <%= form.label :menuindex, 'Расположение картинки в слоях изображения для авито', class: 'form-label' %>
    <%= form.number_field :menuindex, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :client_id, class: 'form-label' %>
    <%= form.text_field :client_id, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :client_secret, class: 'form-label' %>
    <%= form.text_field :client_secret, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :percent, class: 'form-label' %>
    <%= form.number_field :percent, class: 'form-control', min: -100, max: 100 %>
  </div>

  <div class="mb-3">
    <%= form.check_box :active, { checked: @store.active, class: 'form-check-input' } %>
    <%= form.label :active, class: 'form-check-label' %>
  </div>

  <div class="mb-3">
    <%= form.submit (method == :patch ? 'Save' : 'Add'), class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/stores/_store.html.erb
<li class="list-group-item list-group-item-action d-flex<%= active_item(store) %>" id="store_<%= store.id %>">
  <div style="width: 100%; padding-left: 10px;">
    <div class="row">
      <div class="col-7 col-md-10">
        <div class="row">
          <div class="col-12 col-md-6">
            <%= link_to store.manager_name, store_path(store.id) %>
            <% if store.percent != 0 %>
              <span class="ms-1 badge text-bg-<%= store.percent > 0 ? 'success' : 'danger' %>">
                <%= store.percent %>%
              </span>
            <% end %>
          </div>
          <div class="col-12 col-md-6 mt-1 mt-md-0">
            <span><i class="bi bi-telephone"></i> <%= store.contact_phone %></span>
          </div>
        </div>
      </div>

      <div class="col-5 col-md-2 d-flex justify-content-end align-items-center gap-2" title="<%= store.active ? 'Активен' : 'Не активен' %>">
        <% if store.active %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-toggle-on" viewBox="0 0 16 16">
            <path d="M5 3a5 5 0 0 0 0 10h6a5 5 0 0 0 0-10zm6 9a4 4 0 1 1 0-8 4 4 0 0 1 0 8"/>
          </svg>
        <% else %>
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-toggle-off" viewBox="0 0 16 16">
            <path d="M11 4a4 4 0 0 1 0 8H8a5 5 0 0 0 2-4 5 5 0 0 0-2-4zm-6 8a4 4 0 1 1 0-8 4 4 0 0 1 0 8M0 8a5 5 0 0 0 5 5h6a5 5 0 0 0 0-10H5a5 5 0 0 0-5 5"/>
          </svg>
        <% end %>

        <%= link_to edit_store_path(store.id), class: "btn btn-warning btn-sm",
                    style: 'max-height: 39px;', title: 'Править' do %>
          <i class="bi bi-pen"></i>
        <% end %>

        <div style="display: inline-block;">
          <%= button_to store_path(store.id), method: :delete, class: 'btn btn-danger btn-sm', title: 'Удалить магазин',
                        data: { confirm: 'Are you sure you want to delete this store?',
                                controller: 'confirm', action: 'click->confirm#call' } do %>
            <i class="bi bi-trash"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/stores/_test_img.html.erb
<% if @store.test_img.attached? %>
  <h5>Тестовая картинка</h5>
  <%= link_to '', data: { controller: "fancybox", fancybox: "gallery-test", src: url_for(@store.test_img) } do %>
    <div style="background-image: url(<%= url_for(@store.test_img) %>); background-size: contain;
      width: 198px; height: 144px; background-repeat: no-repeat;"></div>
  <% end %>
<% end %>

app/views/stores/edit.html.erb
<% content_for :title do %>
  Редактирование магазина <%= @store.manager_name %>
<% end %>

<%= turbo_frame_tag @store do %>
  <div class="container">
    <%= render partial: '/stores/form', locals: { url: store_path(@store), method: :patch } %>
  </div>
<% end %>

app/views/stores/index.html.erb
<% content_for :title do %>
  Магазины
<% end %>

<div class="container">
  <a href="<%= new_store_path %>" class="btn btn-success mb-3">Add</a>
  <ol class="list-group list-group-numbered">
    <%= render @stores %>
  </ol>
</div>

app/views/stores/new.html.erb
<% content_for :title do %>
  Создать новый магазин
<% end %>

<div class="container">
  <%= render partial: '/stores/form', locals: { url: stores_path, method: :past } %>
</div>

app/views/stores/show.html.erb
<% content_for :title do %>
  Магазин <%= @store.manager_name %>
  <% if !@store.percent.zero? %>
    <span class="percent"><%= '+' if @store.percent.positive?  %><%= "#{@store.percent}" %>%</span>
  <% end %>
<% end %>

<% content_for :head do %>
  <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=369d354e-0df0-4d9d-bb3a-08bc6a532a15" type="text/javascript"></script>
<% end %>

<%= turbo_frame_tag @store do %>
  <div class="container">
    <div class="d-flex gap-3">
      <%= button_to 'Обновить feed', store_update_feed_path(@store),
                    class: 'loader-btn btn btn-success btn-upd-feed',
                    data: { controller: 'btn_preloader', action: 'click->btn_preloader#call' } %>

      <%= button_to 'Обновить Black list', store_update_ban_list_path(@store),
                    class: 'loader-btn btn btn-dark' %>
      <%= link_to 'Авито', store_avito_dashboard_path(@store), class: 'btn btn-primary', data: { turbo: false } %>
    </div>

    <ul class="nav nav-tabs mt-2 mt-md-3" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#home" type="button" role="tab" aria-controls="home" aria-selected="true">Основная информация</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="address-tab" data-bs-toggle="tab" data-bs-target="#address" type="button" role="tab" aria-controls="address" aria-selected="false">Адреса магазина</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="profile-tab" data-bs-toggle="tab" data-bs-target="#profile" type="button" role="tab" aria-controls="profile" aria-selected="false">Слои картинки</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link" id="adss-tab" data-bs-toggle="tab" data-bs-target="#adss" type="button" role="tab" aria-controls="adss-block" aria-selected="false">Объявления</button>
      </li>
    </ul>

    <div class="tab-content mt-3" id="myTabContent">
      <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
        <a href="<%= edit_store_path(@store.id) %>" class='mb-3 btn btn-warning'>Edite</a>

        <ul class="list-group">
          <% @store.attributes.each do |key, value| %>
            <% next if key.match?(/^id|created_at|updated_at/) %>

            <li class="list-group-item list-group-item-action overflow-hidden">
              <strong><%= key %>: </strong>
              <%= key.match?(/description|desc_game|desc_product/) ? sanitize_description(value) : value %>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="tab-pane fade" id="address" role="tabpanel" aria-labelledby="address-tab">
        <%= render partial: '/addresses/new_address_btn', locals: { store: @store } %>

        <ul class="list-group mb-3" id="addresses">
          <%= render @addresses %>
        </ul>
        <%= turbo_frame_tag :test_img do %>
          <%= render partial: '/stores/test_img' %>
        <% end %>
      </div>

      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <%= render partial: '/image_layers/new_image_layer_btn', locals: { store: @store } %>

        <ol class="list-group list-group-numbered" id="image_layers">
          <%= render @image_layers %>
        </ol>
      </div>

      <div class="tab-pane fade" id="adss" role="tabpanel" aria-labelledby="adss-tab">
        <%= turbo_frame_tag :ads do %>
          <%= render partial: '/ads/ads_list' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>