config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable' if Rails.env.production?
  # get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { registrations: 'registrations' }

  authenticate :user do
    mount GoodJob::Engine => '/good_job'
    mount ExceptionTrack::Engine => '/exception-track'
    mount RailsPerformance::Engine => '/performance'
    mount PgHero::Engine => '/pghero'
  end

  root 'feeds#index'

  resources :settings, only: %i[index create update]
  resources :games, only: %i[index show destroy]
  resources :game_black_lists, only: %i[index create destroy]
  resources :products
  resources :image_layers, only: %i[new create show update destroy]
  resources :avitos, only: [:index]
  post '/update_img', to: 'jobs#update_img'
  get '/feeds', to: 'feeds#index'

  resources :stores do
    draw :avito
    get '/avito', to: 'avito/dashboard#index'

    post '/update_feed', to: 'jobs#update_feed', as: 'update_feed'
    post '/update_ban_list', to: 'jobs#update_ban_list'
    post '/update_store_test_img', to: 'jobs#update_store_test_img'
    patch '/update_all', to: 'ads#update_all'

    resources :streets, only: %i[index create update destroy]
    resources :maps, only: [:show]
    resources :addresses, only: %i[new create show update destroy]
    resources :ads, only: %i[edit update]
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :authenticate_user!, :set_store, :set_address

  def show
    return error_notice('Error getting address') if @address.nil?

    @all_store = current_user.stores.active.includes(:addresses).where(addresses: { active: true }) if params[:all]
    render turbo_stream: [
      turbo_stream.replace("address_#{@address.id}", partial: '/maps/map', locals: { address: @address })
    ]
  end

  private

  def set_address
    @address = @store.addresses.find(params[:address_id]) if @store
  end
end

app/views/maps/_map.html.erb
<li class="list-group-item list-group-item-action" id="address_<%= @address.id %>">
  <div class="row mb-2">
    <div class="col-11">
      <h5>Покрытие <%= @address.city %>:</h5>
    </div>
    <div class="col-1">
      <div class="d-flex justify-content-end">
        <%= link_to store_address_path(id: @address, store_id: @address.store), title: 'Назад',
                    class: 'btn btn-primary btn-sm', data: { turbo_prefetch: false } do %>
          <i class="bi bi-backspace"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div data-controller="map">
    <div data-map-target="addresses" style="display: none">
      <% if @all_store.present? %>
        <% @all_store.each do |store| %>
          <% store.addresses.active.each do |address| %>
            <% address.streets.each do |street| %>
              <span><%= "#{address.city}, #{street.title}" %></span>
            <% end %>
          <% end %>
        <% end %>
      <% else %>
        <% @address.streets.each do |street| %>
          <span><%= "#{@address.city}, #{street.title}" %></span>
        <% end %>
      <% end %>
    </div>
    <div id="map" class="mb-3" data-map-target="map"></div>
  </div>
</li>