config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable' if Rails.env.production?
  # get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: { registrations: 'registrations' }

  authenticate :user do
    mount GoodJob::Engine => '/good_job'
    mount ExceptionTrack::Engine => '/exception-track'
    mount RailsPerformance::Engine => '/performance'
    mount PgHero::Engine => '/pghero'
  end

  root 'feeds#index'

  resources :settings, only: %i[index create update]
  resources :games, only: %i[index show destroy]
  resources :game_black_lists, only: %i[index create destroy]
  resources :products
  resources :image_layers, only: %i[new create show update destroy]
  resources :avitos, only: [:index]
  post '/update_img', to: 'jobs#update_img'
  get '/feeds', to: 'feeds#index'

  resources :stores do
    draw :avito
    get '/avito', to: 'avito/dashboard#index'

    post '/update_feed', to: 'jobs#update_feed', as: 'update_feed'
    post '/update_ban_list', to: 'jobs#update_ban_list'
    post '/update_store_test_img', to: 'jobs#update_store_test_img'
    patch '/update_all', to: 'ads#update_all'

    resources :streets, only: %i[index create update destroy]
    resources :maps, only: [:show]
    resources :addresses, only: %i[new create show update destroy]
    resources :ads, only: %i[edit update]
  end
end

app/models/image_layer.rb
class ImageLayer < ApplicationRecord
  has_one_attached :layer, dependent: :purge # , service: (Rails.env.test? ? :test : :local)
  belongs_to :store

  validate :check_img_title, on: %i[update create]

  enum :layer_type, { img: 0, platform: 1, text: 2, flag: 3 }

  before_save :set_default_menuindex, :set_default_layer_params

  scope :active, -> { where(active: true) }

  private

  def set_default_menuindex
    return if menuindex.present?

    max_menuindex  = ImageLayer.maximum(:menuindex)
    self.menuindex = max_menuindex ? max_menuindex + 1 : 1
  end

  def set_default_layer_params
    layer_params.present? || self.layer_params = nil
  end

  def check_img_title
    errors.add(:base, 'Должна быть указана картинка или текст слоя!') if layer.blank? && title.blank?
  end
end

app/controllers/image_layers_controller.rb
class ImageLayersController < ApplicationController
  before_action :authenticate_user!, :set_store
  before_action :set_layer, only: %i[update destroy]

  def new
    @image_layer = @store.image_layers.build
    render turbo_stream: [
      turbo_stream.prepend(:image_layers, partial: 'image_layers/new'),
      turbo_stream.remove(:new_image_layer_btn)
    ]
  end

  def create
    @layer = @store.image_layers.build(image_layer_params)
    return handle_successful_save if @layer.save

    error_notice(@layer.errors.full_messages)
  end

  def update
    return handle_successful_update if @layer.update(image_layer_params)

    error_notice(@layer.errors.full_messages)
  end

  def destroy
    if @layer.destroy
      msg = "Слой #{@layer.menuindex} был успешно удален."
      render turbo_stream: [turbo_stream.remove("image_layer_#{@layer.id}"), success_notice(msg)]
    else
      error_notice(@layer.errors.full_messages)
    end
  end

  private

  def set_layer
    @layer = @store.image_layers.find(params[:id])
  end

  def image_layer_params
    params.require(:image_layer).permit(:layer_type, :title, :menuindex, :layer_params, :layer, :active)
  end

  def handle_successful_save
    msg = ["Слой под номером #{@layer.menuindex} был успешно добавлен."]
    msg << 'Внимание слой не активен!' if image_layer_params[:active].to_i.zero?
    render turbo_stream: [
      turbo_stream.append(:image_layers, partial: 'image_layers/image_layer', locals: { image_layer: @layer }),
      turbo_stream.remove(:new_image_layers),
      turbo_stream.before(:image_layers, partial: 'image_layers/new_image_layer_btn', locals: { store: @store }),
      success_notice(msg)
    ]
  end

  def handle_successful_update
    msg = ["Слой под номером #{@layer.menuindex} был успешно обновлен."]
    msg << 'Внимание слой не активен!' if image_layer_params[:active].to_i.zero?
    render turbo_stream: [
      turbo_stream.replace("image_layer_#{@layer.id}",
                           partial: 'image_layers/image_layer',
                           locals: { image_layer: @layer }),
      success_notice(msg)
    ]
  end
end

app/views/image_layers/_form.html.erb
<%= form_with(model: image_layer, url: url, method: method) do |form| %>
  <div class="row">
    <div class="col-4 col-md-1">
      <div style="max-height: 70px; overflow: hidden; color: green; word-wrap: break-word;">
        <% if image_layer.layer.attached? %>
          <% if image_layer.layer.blob.content_type.match?(/font/) %>
            <%= image_layer.layer.blob.filename %>
          <% else %>
            <%= link_to '', data: { controller: "fancybox", fancybox: "gallery", src: url_for(image_layer.layer) } do %>
              <div style="background-image: url(<%= url_for(image_layer.layer) %>); background-size: contain;
                width: 100%; height: 70px; background-repeat: no-repeat;"></div>
            <% end %>
          <% end %>
        <% else %>
          <span style="color: red; font-size: 0.8rem;">Шрифт или картинка не указан!</span>
        <% end %>
      </div>
    </div>

    <div class="col-8 col-md-3">
      <%= form.label :layer, 'Картинка или шрифт', class: 'form-label' %>
      <%= form.file_field :layer, value: image_layer.layer.blob&.filename, class: 'form-control',
                          accept: 'image/jpeg, image/png, image/webp, font/ttf' %>
    </div>

    <div class="col-8 col-md-2">
      <%= form.label :layer_type, class: 'form-label' %>
      <%= form.select :layer_type,
                      ImageLayer.layer_types.keys.map { |type| [type.humanize, type] }, {}, { class: 'form-select' } %>
    </div>

    <div class="col-4 col-md-1">
      <%= form.label :menuindex, class: 'form-label' %>
      <%= form.text_field :menuindex, value: image_layer.menuindex, class: 'form-control' %>
    </div>

    <div class="col-12 col-md-5 mb-3 mb-md-0">
      <%= form.label :title, class: 'form-label' %>
      <%= form.text_field :title, value: image_layer.title, class: 'form-control' %>
    </div>

    <div class="col-12 col-md-11 mb-3">
      <%= form.label :layer_params, class: 'form-label' %>
      <%= form.text_field :layer_params, value: image_layer.layer_params, class: 'form-control',
                          placeholder: { pointsize: 64, row: 400, column: 100, pos_x: 448, pos_y: 120 } %>
    </div>

    <div class="col-12 col-md-1 mt-0 mt-md-2 d-flex d-md-block justify-content-between">
      <div>
        <%= form.check_box :active, class: 'form-check-input', id: "active_#{image_layer.id}" %>
        <%= form.label :active, value: image_layer.active, class: 'form-check-label', for: "active_#{image_layer.id}" %>
      </div>

      <% if method == :post %>
        <%= form.submit 'Add', class: 'mt-0 mt-md-2 btn btn-primary btn-sm' %>
      <% else %>
        <%= form.submit 'Save', class: 'mt-0 mt-md-2 btn btn-warning btn-sm' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/image_layers/_image_layer.html.erb
<li class="list-group-item list-group-item-action <%= active_item(image_layer) %>" id="image_layer_<%= image_layer.id %>">
  <b>Слой</b>
  <%= render partial: '/image_layers/form',
             locals: { image_layer: image_layer,
                       url: image_layer_path(id: image_layer, store_id: image_layer.store), method: :patch } %>

  <%= button_to image_layer_path(id: image_layer, store_id: image_layer.store),
                method: :delete, class: 'del-layer-btn',
                data: { confirm: 'Вы уверены, что хотите удалить слой?',
                        controller: 'confirm', action: 'click->confirm#call' } do %>
    <i class="bi bi-x-lg"></i>
  <% end %>
</li>

app/views/image_layers/_new.html.erb
<li class="list-group-item list-group-item-action list-group-item-success" id="new_image_layers">
  <b>Новый слой</b>
  <%= render partial: '/image_layers/form', locals: { image_layer: @image_layer,
                                                      url: image_layers_path(store_id: @image_layer.store),
                                                      method: :post } %>
</li>

app/views/image_layers/_new_image_layer_btn.html.erb
<%= link_to 'Новый слой', new_image_layer_path(store_id: store), class: 'btn btn-primary mb-3',
            data: { turbo_prefetch: false }, id: :new_image_layer_btn %>